/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dustbin_management;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Manish
 */
public class cleaner_incharge extends javax.swing.JFrame {

    /**
     * Creates new form cleaner_incharge
     */
    public cleaner_incharge() {
        initComponents();
    }

    int k = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dustid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        print = new javax.swing.JTextArea();
        jl1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLEANER IN-CHARGE WORKSPACE ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 110));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dustbin ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 89, 25));

        dustid.setBackground(new java.awt.Color(0, 51, 102));
        dustid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dustid.setForeground(new java.awt.Color(255, 255, 255));
        dustid.setBorder(null);
        dustid.setCaretColor(new java.awt.Color(255, 255, 255));
        dustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dustidActionPerformed(evt);
            }
        });
        jPanel2.add(dustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 248, 25));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 248, 10));

        print.setEditable(false);
        print.setBackground(new java.awt.Color(51, 37, 78));
        print.setColumns(20);
        print.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setRows(5);
        print.setBorder(null);
        jScrollPane1.setViewportView(print);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 390, 220));

        jl1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl1.setText("DUSTBIN STATUS");
        jl1.setEnabled(false);
        jPanel2.add(jl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 134, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_broom_60px.png"))); // NOI18N
        jButton2.setText("CLEAN");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_48px.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 760, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dustidActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dustidActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_dustidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(k == 0)
            return;
            
        try{
            String URL = "jdbc:mysql://localhost:3306/smart_dustbin";
            String USER_NAME = "manish";
            String PASSWORD = "manish";
            String query="UPDATE dustbin SET Level = 0 where Dustbin_ID = ?";
            
            Connection conn = DriverManager.getConnection(URL, USER_NAME, PASSWORD);;
            PreparedStatement stmt = conn.prepareStatement(query);;
            stmt.setString(1, Integer.toString(dustbin_management.Dustbin_Management.dustbinlist.get(k).id));
            stmt.executeUpdate();

            dustbin_management.Dustbin_Management.dustbinlist.get(k).level = 0;
            JOptionPane.showMessageDialog(null, "Dustbin Cleared successfully", "Cleared", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
        
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton2MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int ID = 0;
        try{
            ID = Integer.parseInt(dustid.getText());
        }
        catch (NumberFormatException ex){
            System.out.println(ex);
        }

        int flag = 0;
        for (int i = 0; i < dustbin_management.Dustbin_Management.dustbinlist.size(); i++) {

            if (dustbin_management.Dustbin_Management.dustbinlist.get(i).id == ID) {
                flag = 1;
                k = i;
            }
        }
        if (flag == 0) {
            k=0;
            print.setText("");
            JOptionPane.showMessageDialog(null, "Invaid Dustbin Id", "Dustbin not registered",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            // SHOW DETAILS...
            String LOCATION = dustbin_management.Dustbin_Management.dustbinlist.get(k).location;
            double WIDTH = dustbin_management.Dustbin_Management.dustbinlist.get(k).width;
            double HEIGHT = dustbin_management.Dustbin_Management.dustbinlist.get(k).height;
            int LEVEL = dustbin_management.Dustbin_Management.dustbinlist.get(k).level;
            String LASTEMPTYDATE = dustbin_management.Dustbin_Management.dustbinlist.get(k).lastEmptyDate;

            print.setText("Location: " + LOCATION + "\n\n" + "Width: " + WIDTH + "\n\n" + "Height: " + HEIGHT + "\n\n"
                    + "Level: " + LEVEL + "\n\n" + "Last Empty Date: " + LASTEMPTYDATE);

        }

    }// GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cleaner_incharge.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cleaner_incharge.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cleaner_incharge.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cleaner_incharge.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cleaner_incharge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dustid;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jl1;
    private javax.swing.JTextArea print;
    // End of variables declaration//GEN-END:variables
}
